#!/usr/bin/env python
"""
Build the G'Day model and add Git revision tag to _version.py

that's all folks.
"""
__author__ = "Martin De Kauwe"
__version__ = "1.0 (05.12.2014)"
__email__ = "mdekauwe@gmail.com"

import os, subprocess, re
from distutils.core import setup, Command

import subprocess

def info(x):
    gitArg = ["git"]
    gitArg.extend(x)
    git_info = subprocess.check_output(gitArg)
    return(git_info.split('\n'))

VERSION_PY = """
# This file is automatically generated with the relevant Git info
# by running 'setup.py version'
# Or just run the Makefile!

__version__ = '%s'
"""

def update_version_py():
    if not os.path.isdir(".git"):
        print "This does not appear to be a Git repository."
        return
    try:
        ver = info(["rev-parse","HEAD"])[0]
    except EnvironmentError:
        print "unable to run git, leaving src/_version.py alone"
        return
        
    def makeHook(fname):
        path = ".git/hooks/"
        fname = path + fname
        #import pdb; pdb.set_trace()
        if not os.path.isdir(fname):
            #subprocess.call( ["cp", "setup.py", fname] )
            subprocess.call( ["cp", path + "pre-commit.sample", fname] )
            
            f = open(fname, "w")
            f.write("#!/bin/sh \nsudo make install")
            f.close()
             
    for i in ['post-checkout', 'post-commit', 'post-merge']: makeHook(i)
        
    f = open("src/_version.py", "w")
    f.write(VERSION_PY % ver)
    f.close()
    print "set src/_version.py to '%s'" % ver

def get_version():
    try:
        f = open("src/_version.py")
    except EnvironmentError:
        return None
    for line in f.readlines():
        mo = re.match("__version__ = '([^']+)'", line)
        if mo:
            ver = mo.group(1)
            return ver
    return None

class Version(Command):
    description = "update _version.py from Git repo"
    user_options = []
    boolean_options = []
    def initialize_options(self):
        pass
    def finalize_options(self):
        pass
    def run(self):
        update_version_py()
        print "Version is now", get_version()


setup(name="pygday",
    version=get_version(),
    description="A Python implementation of the G'DAY (Generic Decomposition And Yield) model",
    long_description="GDAY model, simulates the cycling of C, N and water in plants and soil",
    author="Martin De Kauwe",
    author_email='mdekauwe@gmail.com',
    platforms = ['any'],
    package_dir = {'gday': 'src'},
    packages = ['gday'],
    cmdclass={"version": Version },
)